filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php: {  }
build:
  tests:
    override:
      -
        command: 'bin/phpunit --coverage-clover=coverage.xml'
        coverage:
          file: 'clover.xml'
          format: 'clover'